name: CI
on: [ push, pull_request ]


jobs:
  lint-and-test:
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository
    runs-on: ubuntu-22.04
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v3

      - name: Run linter
        run: |
          shellcheck bin/*
          shellcheck -P SCRIPTDIR -x test/utils test/test-*

      - run: ./run_tests.sh

  test-macos:
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository
    runs-on: macos-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v3

      - run: ./run_tests.sh
